# -*- coding: utf-8 -*-
"""ETC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HUmK_5r-RCTYi6HsE0MeCL_yP0tht2j

Import Dataset & Packages
"""

import pulp
import streamlit as st
import numpy as np
import pandas as pd
import altair as alt
from datetime import datetime, timedelta

file_path = '/content/Capstone Budget Data.xlsx'
df = pd.read_excel(file_path)
display(df.head())

"""Linear Model"""



"""StreamLit Integration"""

import streamlit as st
import pandas as pd

st.title("My App")

name = st.text_input("Enter your name")
if name:
    st.write(f"Hello, {name}!")

df = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
st.dataframe(df)
st.line_chart(df.set_index("x"))

